name: Publish

on:
  push:
    tags:
      - 'v0.2'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: mvn -B package --file ScrumTool/pom.xml
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: ScrumTool/target/ScrumTool-1.0-SNAPSHOT.jar
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
